
#include "../../os/include/extern.h"
#include "../../os/include/audio.h"
#include "../../os/include/graphics.h"
#include "../../os/include/filesys.h"
#include "../../os/include/disk.h"
#include "../../os/include/scheduler.h"
#include "../../os/include/network.h"
#include "../../os/include/input.h"
#include "../../os/include/memory.h"
#include "../../os/include/terminal.h"
